apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-hello-world
  template:
    metadata:
      labels:
        app: fastapi-hello-world
    spec:
      containers:
      - name: fastapi-hello-world
        image: fastapi-hello-world:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-hello-world-service
spec:
  type: NodePort
  selector:
    app: fastapi-hello-world
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
